### PR TITLE
Removing autoloading the utility

### PR DESCRIPTION
**Pull request by bloodbare**

### CODE REVIEW

**Comment by vangheem** [comment]
Argh, yah, this shouldn't be here. It would get registered twice I think. Does this cause problems?

**Review by vangheem — APPROVED** [review]

**Comment by vangheem** [comment]
Can we have a changelog entry?

**Review by vangheem — CHANGES_REQUESTED** [review]
changelog

**Comment by bloodbare** [comment]
> Argh, yah, this shouldn't be here. It would get registered twice I think. Does this cause problems?

We are lucky that initializer does not get called by registration, because its loaded twice

**Comment by bloodbare** [comment]
As redis cache is a reprecated package for guillotina I’m closing this PR

**Pull request closed without merging**
